[[authors]]
email = "liyichen20000104@outlook.com"
name.default = "Yichen Li"

[[wallpapers]]
title.default = "Jade Dragon"
title.zh-CN = "玉龙雪山"
license = "CC BY-SA 4.0"
id = "Jade_Dragon"
path = "Jade_Dragon.jpg"

[[wallpapers]]
title.default = "Lugu"
title.zh-CN = "泸沽湖"
license = "CC BY-SA 4.0"
id = "Lugu"
path = "Lugu.jpg"

[[wallpapers]]
title.default = "Rime"
title.zh-CN = "雾凇"
license = "CC BY-SA 4.0"
id = "Rime"
path = "Rime.jpg"

[[wallpapers]]
title.default = "Seagulls"
title.zh-CN = "海鸥"
license = "CC BY-SA 4.0"
id = "Seagulls"
path = "Seagulls.jpg"
