[[authors]]
email = "rickliu2000@outlook.com"
name.default = "Ruikai Liu"

[[wallpapers]]
title.default = "Capitol Dawn"
title.zh-CN = "暮光之城"
license = "CC BY-NC 4.0"
id = "Capitol_Dawn"
path = "Capitol_Dawn.jpg"

[[wallpapers]]
title.default = "Lake Mendota Blue"
title.zh-CN = "门多塔湖"
license = "CC BY-NC 4.0"
id = "Lake_Mendota_Blue"
path = "Lake_Mendota_Blue.jpg"

[[wallpapers]]
title.default = "Lakeshore Bike Path"
title.zh-CN = "湖畔绿道"
license = "CC BY-NC 4.0"
id = "Lakeshore_Bike_Path"
path = "Lakeshore_Bike_Path.jpg"

[[wallpapers]]
title.default = "Lakeshore in Early Spring"
title.zh-CN = "初春湖畔"
license = "CC BY-NC 4.0"
id = "Lakeshore_in_Early_Spring"
path = "Lakeshore_in_Early_Spring.jpg"

[[wallpapers]]
title.default = "Winter on Mendota"
title.zh-CN = "冰封湖光"
license = "CC BY-NC 4.0"
id = "Winter_on_Mendota"
path = "Winter_on_Mendota.jpg"
