[[authors]]
email = "743387789@qq.com"
name.default = "ALANZ"

[[wallpapers]]
title.default = "Material Tower"
title.zh-CN = "物质塔"
license = "CC BY-NC 4.0"
id = "Material_Tower"
path = "Material_Tower.jpg"
