[[authors]]
email = "cth451@gmail.com"
name.default = "cth451"

[[wallpapers]]
title.default = "Art and Science"
license = "CC BY-NC 4.0"
id = "Art_and_Science"
path = "Art_and_Science.jpg"

[[wallpapers]]
title.default = "Big Steps"
license = "CC BY-NC 4.0"
id = "Big_Steps"
path = "Big_Steps.jpg"

[[wallpapers]]
title.default = "Cloud Forest"
license = "CC BY-NC 4.0"
id = "Cloud_Forest"
path = "Cloud_Forest.jpg"

[[wallpapers]]
title.default = "Edo Ministry"
license = "CC BY-NC 4.0"
id = "Edo_Ministry"
path = "Edo_Ministry.jpg"

[[wallpapers]]
title.default = "Esplanade"
license = "CC BY-NC 4.0"
id = "Esplanade"
path = "Esplanade.jpg"

[[wallpapers]]
title.default = "Fern"
license = "CC BY-NC 4.0"
id = "Fern"
path = "Fern.jpg"

[[wallpapers]]
title.default = "Fireworks"
license = "CC BY-NC 4.0"
id = "Fireworks"
path = "Fireworks.jpg"

[[wallpapers]]
title.default = "Hoodie"
license = "CC BY-NC 4.0"
id = "Hoodie"
path = "Hoodie.jpg"

[[wallpapers]]
title.default = "Kamakura Cherry"
license = "CC BY-NC 4.0"
id = "Kamakura_Cherry"
path = "Kamakura_Cherry.jpg"

[[wallpapers]]
title.default = "Karry"
license = "CC BY-NC 4.0"
id = "Karry"
path = "Karry.jpg"

[[wallpapers]]
title.default = "Land Boulevard at Longfellow Bridge"
license = "CC BY-NC 4.0"
id = "Land_Boulevard_at_Longfellow_Bridge"
path = "Land_Boulevard_at_Longfellow_Bridge.jpg"

[[wallpapers]]
title.default = "Lanterns"
license = "CC BY-NC 4.0"
id = "Lanterns"
path = "Lanterns.jpg"

[[wallpapers]]
title.default = "Luray in Ray"
license = "CC BY-NC 4.0"
id = "Luray_in_Ray"
path = "Luray_in_Ray.jpg"

[[wallpapers]]
title.default = "Luray in Twilight"
license = "CC BY-NC 4.0"
id = "Luray_in_Twilight"
path = "Luray_in_Twilight.jpg"

[[wallpapers]]
title.default = "Mt. Oberlin"
license = "CC BY-NC 4.0"
id = "Mt._Oberlin"
path = "Mt._Oberlin.jpg"

[[wallpapers]]
title.default = "O-dori Sta"
license = "CC BY-NC 4.0"
id = "O-dori_Sta"
path = "O-dori_Sta.jpg"

[[wallpapers]]
title.default = "Oat Grass"
license = "CC BY-NC 4.0"
id = "Oat_Grass"
path = "Oat_Grass.jpg"

[[wallpapers]]
title.default = "Presque Isle Beach 11"
license = "CC BY-NC 4.0"
id = "Presque_Isle_Beach_11"
path = "Presque_Isle_Beach_11.jpg"

[[wallpapers]]
title.default = "Presque Isle Light"
license = "CC BY-NC 4.0"
id = "Presque_Isle_Light"
path = "Presque_Isle_Light.jpg"

[[wallpapers]]
title.default = "Route 20"
license = "CC BY-NC 4.0"
id = "Route_20"
path = "Route_20.jpg"

[[wallpapers]]
title.default = "South Vaulted Walkway"
license = "CC BY-NC 4.0"
id = "South_Vaulted_Walkway"
path = "South_Vaulted_Walkway.jpg"

[[wallpapers]]
title.default = "St. Mary Lake"
license = "CC BY-NC 4.0"
id = "St._Mary_Lake"
path = "St._Mary_Lake.jpg"

[[wallpapers]]
title.default = "Strafford Station"
license = "CC BY-NC 4.0"
id = "Strafford_Station"
path = "Strafford_Station.jpg"

[[wallpapers]]
title.default = "Take a Peek"
license = "CC BY-NC 4.0"
id = "Take_a_Peek"
path = "Take_a_Peek.jpg"

[[wallpapers]]
title.default = "The Gardiner"
license = "CC BY-NC 4.0"
id = "The_Gardiner"
path = "The_Gardiner.jpg"

[[wallpapers]]
title.default = "Theatres on the Bay"
license = "CC BY-NC 4.0"
id = "Theatres_on_the_Bay"
path = "Theatres_on_the_Bay.jpg"

[[wallpapers]]
title.default = "Traffic Lights"
license = "CC BY-NC 4.0"
id = "Traffic_Lights"
path = "Traffic_Lights.jpg"

[[wallpapers]]
title.default = "Train to Malvern"
license = "CC BY-NC 4.0"
id = "Train_to_Malvern"
path = "Train_to_Malvern.jpg"

[[wallpapers]]
title.default = "Union"
license = "CC BY-NC 4.0"
id = "Union"
path = "Union.jpg"
