[[authors]]
email = "jeffbai@aosc.io"
name.default = "Mingcong Bai"

[[wallpapers]]
title.default = "Auspicious Clouds"
license = "CC BY-NC 4.0"
id = "Auspicious_Clouds"
path = "Auspicious_Clouds.jpg"

[[wallpapers]]
title.default = "Extraterrestrial"
license = "CC BY-NC 4.0"
id = "Extraterrestrial"
path = "Extraterrestrial.jpg"

[[wallpapers]]
title.default = "Far Afield"
license = "CC BY-NC 4.0"
id = "Far_Afield"
path = "Far_Afield.jpg"

[[wallpapers]]
title.default = "Ice Plants"
license = "CC BY-NC 4.0"
id = "Ice_Plants"
path = "Ice_Plants.jpg"

[[wallpapers]]
title.default = "Lux Adoris"
license = "CC BY-NC 4.0"
id = "Lux_Adoris"
path = "Lux_Adoris.jpg"

[[wallpapers]]
title.default = "Turf"
license = "CC BY-NC 4.0"
id = "Turf"
path = "Turf.jpg"

[[wallpapers]]
title.default = "Vista"
license = "CC BY-NC 4.0"
id = "Vista"
path = "Vista.jpg"
