[[authors]]
email = "jeffbai@aosc.io"
name.default = "Mingcong Bai"
name.zh-CN = "白铭骢"

[[wallpapers]]
title.default = "Basking in Nature"
title.zh-CN = "光荫"
license = "CC BY-NC 4.0"
id = "Basking_in_Nature"
path = "Basking_in_Nature.jpg"

[[wallpapers]]
title.default = "Bee's Heaven"
title.zh-CN = "蜂与花"
license = "CC BY-NC 4.0"
id = "Bees_Heaven"
path = "Bees_Heaven.jpg"

[[wallpapers]]
title.default = "Bleak Daylight"
title.zh-CN = "酷日"
license = "CC BY-NC 4.0"
id = "Bleak_Daylight"
path = "Bleak_Daylight.jpg"

[[wallpapers]]
title.default = "Bliss"
title.zh-CN = "逍遥"
license = "CC BY-NC 4.0"
id = "Bliss"
path = "Bliss.jpg"

[[wallpapers]]
title.default = "Blissful Dusk"
title.zh-CN = "陶陶霞光"
license = "CC BY-NC 4.0"
id = "Blissful_Dusk"
path = "Blissful_Dusk.jpg"

[[wallpapers]]
title.default = "Blissful Electrons"
title.zh-CN = "乐与电光"
license = "CC BY-NC 4.0"
id = "Blissful_Electrons"
path = "Blissful_Electrons.jpg"

[[wallpapers]]
title.default = "Canyonlands"
title.zh-CN = "峡谷地"
license = "CC BY-NC 4.0"
id = "Canyonlands"
path = "Canyonlands.jpg"

[[wallpapers]]
title.default = "Chicane"
title.zh-CN = "流光回转"
license = "CC BY-NC 4.0"
id = "Chicane"
path = "Chicane.jpg"

[[wallpapers]]
title.default = "Closing Time"
title.zh-CN = "落暮"
license = "CC BY-NC 4.0"
id = "Closing_Time"
path = "Closing_Time.jpg"

[[wallpapers]]
title.default = "Clover Rover"
title.zh-CN = "三叶迷踪"
license = "CC BY-NC 4.0"
id = "Clover_Rover"
path = "Clover_Rover.jpg"

[[wallpapers]]
title.default = "Collapse"
title.zh-CN = "屈服"
license = "CC BY-NC 4.0"
id = "Collapse"
path = "Collapse.jpg"

[[wallpapers]]
title.default = "Desert Rain"
title.zh-CN = "甘霖"
license = "CC BY-NC 4.0"
id = "Desert_Rain"
path = "Desert_Rain.jpg"

[[wallpapers]]
title.default = "Desert of Life"
title.zh-CN = "绝境"
license = "CC BY-NC 4.0"
id = "Desert_of_Life"
path = "Desert_of_Life.jpg"

[[wallpapers]]
title.default = "Devils Tower"
title.zh-CN = "魔鬼塔"
license = "CC BY-NC 4.0"
id = "Devils_Tower"
path = "Devils_Tower.jpg"

[[wallpapers]]
title.default = "Dinky Flowers"
title.zh-CN = "小薇"
license = "CC BY-NC 4.0"
id = "Dinky_Flowers"
path = "Dinky_Flowers.jpg"

[[wallpapers]]
title.default = "Lust"
title.zh-CN = "爱慕"
license = "CC BY-NC 4.0"
id = "Ducklings"
path = "Ducklings.jpg"

[[wallpapers]]
title.default = "Flowers in the Woods"
title.zh-CN = "林间小花"
license = "CC BY-NC 4.0"
id = "Flowers_in_the_Woods"
path = "Flowers_in_the_Woods.jpg"

[[wallpapers]]
title.default = "Flying Away"
title.zh-CN = "归雁"
license = "CC BY-NC 4.0"
id = "Flying_Away"
path = "Flying_Away.jpg"

[[wallpapers]]
title.default = "Forsaken Frontier"
title.zh-CN = "末日放逐"
license = "CC BY-NC 4.0"
id = "Forsaken_Frontier"
path = "Forsaken_Frontier.jpg"

[[wallpapers]]
title.default = "Full Moon 2"
title.zh-CN = "满月 2"
license = "CC BY-NC 4.0"
id = "Full_Moon"
path = "Full_Moon.jpg"

[[wallpapers]]
title.default = "Liquid Jade"
title.zh-CN = "碧水"
license = "CC BY-NC 4.0"
id = "Liquid_Jade"
path = "Liquid_Jade.jpg"

[[wallpapers]]
title.default = "Luna Azul"
title.zh-CN = "日月同辉"
license = "CC BY-NC 4.0"
id = "Luna_Azul"
path = "Luna_Azul.jpg"

[[wallpapers]]
title.default = "Mailbox in Solitude"
title.zh-CN = "孤独信使"
license = "CC BY-NC 4.0"
id = "Mailbox_in_Solitude"
path = "Mailbox_in_Solitude.jpg"

[[wallpapers]]
title.default = "Maroon Bells Autumn"
title.zh-CN = "五彩山林"
license = "CC BY-NC 4.0"
id = "Maroon_Bells_Autumn"
path = "Maroon_Bells_Autumn.jpg"

[[wallpapers]]
title.default = "Mesa"
title.zh-CN = "平顶山"
license = "CC BY-NC 4.0"
id = "Mesa"
path = "Mesa.jpg"

[[wallpapers]]
title.default = "Mesa Arch"
title.zh-CN = "远景之窗"
license = "CC BY-NC 4.0"
id = "Mesa_Arch"
path = "Mesa_Arch.jpg"

[[wallpapers]]
title.default = "Mighty Little People"
title.zh-CN = "人间"
license = "CC BY-NC 4.0"
id = "Mighty_Little_People"
path = "Mighty_Little_People.jpg"

[[wallpapers]]
title.default = "Natural Appreciation"
title.zh-CN = "速写"
license = "CC BY-NC 4.0"
id = "Natural_Appreciation"
path = "Natural_Appreciation.jpg"

[[wallpapers]]
title.default = "Neon of the Seas"
title.zh-CN = "鬼屿"
license = "CC BY-NC 4.0"
id = "Neon_of_the_Seas"
path = "Neon_of_the_Seas.jpg"

[[wallpapers]]
title.default = "Night Light"
title.zh-CN = "峦下霓虹"
license = "CC BY-NC 4.0"
id = "Night_Light"
path = "Night_Light.jpg"

[[wallpapers]]
title.default = "Night at the Pub"
title.zh-CN = "酒干倘卖无"
license = "CC BY-NC 4.0"
id = "Night_at_the_Pub"
path = "Night_at_the_Pub.jpg"

[[wallpapers]]
title.default = "Passing Times"
title.zh-CN = "百无聊赖"
license = "CC BY-NC 4.0"
id = "Passing_Times"
path = "Passing_Times.jpg"

[[wallpapers]]
title.default = "Red Rocks"
title.zh-CN = "红石阵"
license = "CC BY-NC 4.0"
id = "Red_Rocks"
path = "Red_Rocks.jpg"

[[wallpapers]]
title.default = "Regina Caeli"
title.zh-CN = "天擎"
license = "CC BY-NC 4.0"
id = "Regina_Caeli"
path = "Regina_Caeli.jpg"

[[wallpapers]]
title.default = "Resiliance"
title.zh-CN = "漠林"
license = "CC BY-NC 4.0"
id = "Resiliance"
path = "Resiliance.jpg"

[[wallpapers]]
title.default = "Road to Bliss"
title.zh-CN = "乐途"
license = "CC BY-NC 4.0"
id = "Road_to_Bliss"
path = "Road_to_Bliss.jpg"

[[wallpapers]]
title.default = "Rushing Fields"
title.zh-CN = "飞奔的田野"
license = "CC BY-NC 4.0"
id = "Rushing_Fields"
path = "Rushing_Fields.jpg"

[[wallpapers]]
title.default = "Sentinels of Wind"
title.zh-CN = "风岚"
license = "CC BY-NC 4.0"
id = "Sentinels_of_Wind"
path = "Sentinels_of_Wind.jpg"

[[wallpapers]]
title.default = "Spring Chicane"
title.zh-CN = "峰回路转"
license = "CC BY-NC 4.0"
id = "Spring_Chicane"
path = "Spring_Chicane.jpg"

[[wallpapers]]
title.default = "Sprouting Hope"
title.zh-CN = "复苏"
license = "CC BY-NC 4.0"
id = "Sprouting_Hope"
path = "Sprouting_Hope.jpg"

[[wallpapers]]
title.default = "Sunset over the Empire"
title.zh-CN = "帝国日暮"
license = "CC BY-NC 4.0"
id = "Sunset_over_the_Empire"
path = "Sunset_over_the_Empire.jpg"

[[wallpapers]]
title.default = "The World Beyond"
title.zh-CN = "异域视界"
license = "CC BY-NC 4.0"
id = "The_World_Beyond"
path = "The_World_Beyond.jpg"

[[wallpapers]]
title.default = "Thorns of Life"
title.zh-CN = "狼棘"
license = "CC BY-NC 4.0"
id = "Thorns_of_Life"
path = "Thorns_of_Life.jpg"

[[wallpapers]]
title.default = "Timothy"
title.zh-CN = "猫尾草"
license = "CC BY-NC 4.0"
id = "Timothy"
path = "Timothy.jpg"

[[wallpapers]]
title.default = "To the Cosmos"
title.zh-CN = "问天"
license = "CC BY-NC 4.0"
id = "To_the_Cosmos"
path = "To_the_Cosmos.jpg"

[[wallpapers]]
title.default = "Toxic Ecstacy"
title.zh-CN = "毒艳"
license = "CC BY-NC 4.0"
id = "Toxic_Ecstacy"
path = "Toxic_Ecstacy.jpg"

[[wallpapers]]
title.default = "Verdant Sea"
title.zh-CN = "海角逢生"
license = "CC BY-NC 4.0"
id = "Verdant_Sea"
path = "Verdant_Sea.jpg"

[[wallpapers]]
title.default = "Voxels"
title.zh-CN = "方圆之地"
license = "CC BY-NC 4.0"
id = "Voxels"
path = "Voxels.jpg"

[[wallpapers]]
title.default = "Windward Gaze"
title.zh-CN = "神往"
license = "CC BY-NC 4.0"
id = "Windward_Gaze"
path = "Windward_Gaze.jpg"

[[wallpapers]]
title.default = "Woody Pond"
title.zh-CN = "林池"
license = "CC BY-NC 4.0"
id = "Woody_Pond"
path = "Woody_Pond.jpg"

[[wallpapers]]
title.default = "Кончится лето"
title.zh-CN = "夏末"
license = "CC BY-NC 4.0"
id = "Кончится_лето"
path = "Кончится_лето.jpg"

[[wallpapers]]
title.default = "Castles of the Sea"
title.zh-CN = "海市"
license = "CC BY-NC 4.0"
id = "Castles_of_the_Sea"
path = "Castles_of_the_Sea.jpg"

[[wallpapers]]
title.default = "Highway Blues"
title.zh-CN = "曲径"
license = "CC BY-NC 4.0"
id = "Highway_Blues"
path = "Highway_Blues.jpg"

[[wallpapers]]
title.default = "This Way Up"
title.zh-CN = "登高"
license = "CC BY-NC 4.0"
id = "This_Way_Up"
path = "This_Way_Up.jpg"
