[[authors]]
email = "cyan@cyano.uk"
name.default = "Cyanoxygen"
name.zh-CN = "老嘟嘟"

[[wallpapers]]
title.default = "Under the Canopy"
title.zh-CN = "荫下"
license = "CC-BY-NC 4.0"
id = "Under_the_Canopy"
path = "Under_the_Canopy.jpg"
