[[authors]]
email = "chuasega1991@gmail.com"
name.default = "James Choi"
name.zh-CN = "阿嘉"

[[wallpapers]]
title.default = "Theatre"
title.zh-CN = "剧院"
license = "CC-BY 4.0"
id = "Theatre"
path = "Theatre.jpg"
