[[authors]]
email = "canarypwn@aosc.io"
name.default = "Alex Qin"

[[wallpapers]]
title.default = "Anza Borrego"
title.zh-CN = "博雷戈沙漠"
license = "CC BY-NC 4.0"
id = "SD_Desert"
path = "SD_Desert.jpg"
