[[authors]]
email = "m0g1c1anyang@gmail.com"
name.default = "m0g1c1an"

[[wallpapers]]
title.default = "Congregation Mickve Israel"
license = "CC BY-NC 4.0"
id = "Congregation_Mickve_Israel"
path = "Congregation_Mickve_Israel.jpg"

[[wallpapers]]
title.default = "Flashback from San Francisco"
license = "CC BY-NC 4.0"
id = "Flashback_from_San_Francisco"
path = "Flashback_from_San_Francisco.jpg"

[[wallpapers]]
title.default = "Lone Wild"
license = "CC BY-NC 4.0"
id = "Lone_Wild"
path = "Lone_Wild.jpg"

[[wallpapers]]
title.default = "St. Brigids Parish"
license = "CC BY-NC 4.0"
id = "St._Brigids_Parish"
path = "St._Brigids_Parish.jpg"

[[wallpapers]]
title.default = "Summer UMass"
license = "CC BY-NC 4.0"
id = "Summer_UMass"
path = "Summer_UMass.jpg"
