[[authors]]
email = "m0g1c14n@gmail.com"
name.default = "Mogician Yang"

[[wallpapers]]
title.default = "Abandoned Sunset"
title.zh-CN = "孤独日落"
license = "CC BY 4.0"
id = "Abandoned_Sunset"
path = "Abandoned_Sunset.jpg"

[[wallpapers]]
title.default = "Corporation Beach 2"
title.zh-CN = "冷海 2"
license = "CC BY 4.0"
id = "Corporation_Beach_II"
path = "Corporation_Beach_II.jpg"

[[wallpapers]]
title.default = "Corporation Beach"
title.zh-CN = "冷海"
license = "CC BY 4.0"
id = "Corporation_Beach"
path = "Corporation_Beach.jpg"

[[wallpapers]]
title.default = "Dune of Weed"
title.zh-CN = "海风"
license = "CC BY 4.0"
id = "Dune_of_Weed"
path = "Dune_of_Weed.jpg"

[[wallpapers]]
title.default = "The Crest"
title.zh-CN = "海甸"
license = "CC BY 4.0"
id = "The_Crest"
path = "The_Crest.jpg"

[[wallpapers]]
title.default = "The Thrill is Gone"
title.zh-CN = "渐入佳境"
license = "CC BY 4.0"
id = "The_Thrill_is_Gone"
path = "The_Thrill_is_Gone.jpg"
