[[authors]]
email = "m0g1c14n@gmail.com"
name.default = "Mogician Yang"

[[wallpapers]]
title.default = "Abandoned Sunset"
title.zh-CN = "孤独日落"
license = "CC BY 4.0"
id = "Abandoned_Sunset"
path = "Abandoned_Sunset.jpg"

[[wallpapers]]
title.default = "Corporation Beach 2"
title.zh-CN = "冷海 2"
license = "CC BY 4.0"
id = "Corporation_Beach_II"
path = "Corporation_Beach_II.jpg"

[[wallpapers]]
title.default = "Corporation Beach"
title.zh-CN = "冷海"
license = "CC BY 4.0"
id = "Corporation_Beach"
path = "Corporation_Beach.jpg"

[[wallpapers]]
title.default = "Dune of Weed"
title.zh-CN = "海风"
license = "CC BY 4.0"
id = "Dune_of_Weed"
path = "Dune_of_Weed.jpg"

[[wallpapers]]
title.default = "The Crest"
title.zh-CN = "海甸"
license = "CC BY 4.0"
id = "The_Crest"
path = "The_Crest.jpg"

[[wallpapers]]
title.default = "The Thrill is Gone"
title.zh-CN = "渐入佳境"
license = "CC BY 4.0"
id = "The_Thrill_is_Gone"
path = "The_Thrill_is_Gone.jpg"

[[wallpapers]]
title.default = "Congregation Mickve Israel"
title.zh-CN = "米克维以色列会堂"
license = "CC BY-NC 4.0"
id = "Congregation_Mickve_Israel"
path = "Congregation_Mickve_Israel.jpg"

[[wallpapers]]
title.default = "Flashback from San Francisco"
title.zh-CN = "旧金山剪影"
license = "CC BY-NC 4.0"
id = "Flashback_from_San_Francisco"
path = "Flashback_from_San_Francisco.jpg"

[[wallpapers]]
title.default = "St. Brigid's Parish"
title.zh-CN = "教堂钟塔"
license = "CC BY-NC 4.0"
id = "St._Brigids_Parish"
path = "St._Brigids_Parish.jpg"

[[wallpapers]]
title.default = "Summer UMass"
title.zh-CN = "麻省夏日"
license = "CC BY-NC 4.0"
id = "Summer_UMass"
path = "Summer_UMass.jpg"
