[[authors]]
email = "megabitsenmzq@gmail.com"
name.default = "Megabits"

[[wallpapers]]
title.default = "10th Anniversary - Dark"
license = "CC BY-NC 4.0"
id = "10th_Anniversary_-_Dark"
path = "10th_Anniversary_-_Dark.jpg"

[[wallpapers]]
title.default = "10th Anniversary - Light"
license = "CC BY-NC 4.0"
id = "10th_Anniversary_-_Light"
path = "10th_Anniversary_-_Light.jpg"

[[wallpapers]]
title.default = "10th Anniversary - Retro"
license = "CC BY-NC 4.0"
id = "10th_Anniversary_-_Retro"
path = "10th_Anniversary_-_Retro.jpg"

[[wallpapers]]
title.default = "A Hook in the Mist"
license = "CC BY-NC 4.0"
id = "A_Hook_in_the_Mist"
path = "A_Hook_in_the_Mist.jpg"

[[wallpapers]]
title.default = "Antenna"
license = "CC BY-NC 4.0"
id = "Antenna"
path = "Antenna.jpg"

[[wallpapers]]
title.default = "Antenna - 2"
license = "CC BY-NC 4.0"
id = "Antenna_-_2"
path = "Antenna_-_2.jpg"

[[wallpapers]]
title.default = "Arakawa River"
license = "CC BY-NC 4.0"
id = "Arakawa_River"
path = "Arakawa_River.jpg"

[[wallpapers]]
title.default = "Clock"
license = "CC BY-NC 4.0"
id = "Clock"
path = "Clock.jpg"

[[wallpapers]]
title.default = "Flowers"
license = "CC BY-NC 4.0"
id = "Flowers"
path = "Flowers.jpg"

[[wallpapers]]
title.default = "Flowers - 2"
license = "CC BY-NC 4.0"
id = "Flowers_-_2"
path = "Flowers_-_2.jpg"

[[wallpapers]]
title.default = "Ginkgo"
license = "CC BY-NC 4.0"
id = "Ginkgo"
path = "Ginkgo.jpg"

[[wallpapers]]
title.default = "Leaves"
license = "CC BY-NC 4.0"
id = "Leaves"
path = "Leaves.jpg"

[[wallpapers]]
title.default = "Light"
license = "CC BY-NC 4.0"
id = "Light"
path = "Light.jpg"

[[wallpapers]]
title.default = "Light - 2"
license = "CC BY-NC 4.0"
id = "Light_-_2"
path = "Light_-_2.jpg"

[[wallpapers]]
title.default = "Momiji"
license = "CC BY-NC 4.0"
id = "Momiji"
path = "Momiji.jpg"

[[wallpapers]]
title.default = "Odaiba Sunset"
license = "CC BY-NC 4.0"
id = "Odaiba_Sunset"
path = "Odaiba_Sunset.jpg"

[[wallpapers]]
title.default = "Okutama Lake"
license = "CC BY-NC 4.0"
id = "Okutama_Lake"
path = "Okutama_Lake.jpg"

[[wallpapers]]
title.default = "Petals of Sakura"
license = "CC BY-NC 4.0"
id = "Petals_of_Sakura"
path = "Petals_of_Sakura.jpg"

[[wallpapers]]
title.default = "Piece of Light - Dark"
license = "CC BY-NC 4.0"
id = "Piece_of_Light_-_Dark"
path = "Piece_of_Light_-_Dark.jpg"

[[wallpapers]]
title.default = "Piece of Light - Light"
license = "CC BY-NC 4.0"
id = "Piece_of_Light_-_Light"
path = "Piece_of_Light_-_Light.jpg"

[[wallpapers]]
title.default = "Roof"
license = "CC BY-NC 4.0"
id = "Roof"
path = "Roof.jpg"

[[wallpapers]]
title.default = "Roof - 2"
license = "CC BY-NC 4.0"
id = "Roof_-_2"
path = "Roof_-_2.jpg"

[[wallpapers]]
title.default = "Roof - 3"
license = "CC BY-NC 4.0"
id = "Roof_-_3"
path = "Roof_-_3.jpg"

[[wallpapers]]
title.default = "Roof - 4"
license = "CC BY-NC 4.0"
id = "Roof_-_4"
path = "Roof_-_4.jpg"

[[wallpapers]]
title.default = "Seaside"
license = "CC BY-NC 4.0"
id = "Seaside"
path = "Seaside.jpg"

[[wallpapers]]
title.default = "Seibu Ikebukuro Line"
license = "CC BY-NC 4.0"
id = "Seibu_Ikebukuro_Line"
path = "Seibu_Ikebukuro_Line.jpg"

[[wallpapers]]
title.default = "Sky of Shiinamati"
license = "CC BY-NC 4.0"
id = "Sky_of_Shiinamati"
path = "Sky_of_Shiinamati.jpg"

[[wallpapers]]
title.default = "Snowy Railway"
license = "CC BY-NC 4.0"
id = "Snowy_Railway"
path = "Snowy_Railway.jpg"

[[wallpapers]]
title.default = "The Autumn of the Shrine"
license = "CC BY-NC 4.0"
id = "The_Autumn_of_the_Shrine"
path = "The_Autumn_of_the_Shrine.jpg"

[[wallpapers]]
title.default = "True Blue"
license = "CC BY-NC 4.0"
id = "True_Blue"
path = "True_Blue.jpg"

[[wallpapers]]
title.default = "Utility Pole"
license = "CC BY-NC 4.0"
id = "Utility_Pole"
path = "Utility_Pole.jpg"

[[wallpapers]]
title.default = "Utility Pole - 2"
license = "CC BY-NC 4.0"
id = "Utility_Pole_-_2"
path = "Utility_Pole_-_2.jpg"

[[wallpapers]]
title.default = "Utility Pole - 3"
license = "CC BY-NC 4.0"
id = "Utility_Pole_-_3"
path = "Utility_Pole_-_3.jpg"

[[wallpapers]]
title.default = "Walking on the Bridge"
license = "CC BY-NC 4.0"
id = "Walking_on_the_Bridge"
path = "Walking_on_the_Bridge.jpg"

[[wallpapers]]
title.default = "Yokohama Tasogare"
license = "CC BY-NC 4.0"
id = "Yokohama_Tasogare"
path = "Yokohama_Tasogare.jpg"
