[[authors]]
email = "dev@crh380d.de"
name.default = "Maria Bombadier"

[[wallpapers]]
title.default = "Mai Island"
license = "CC0"
id = "Mai_Island"
path = "Mai_Island.jpg"

[[wallpapers]]
title.default = "Mount Lao"
license = "CC0"
id = "Mount_Lao"
path = "Mount_Lao.jpg"

[[wallpapers]]
title.default = "Watching You"
license = "CC0"
id = "Watching_You"
path = "Watching_You.jpg"

[[wallpapers]]
title.default = "Yellow Sea Vision"
license = "CC0"
id = "Yellow_Sea_Vision"
path = "Yellow_Sea_Vision.jpg"
