[[authors]]
email = "szclsya@aosc.io"
name.default = "Leo Shen"

[[wallpapers]]
title.default = "Dusk"
title.zh-CN = "夜色渐晚"
license = "CC BY-NC-ND 4.0"
id = "Dusk"
path = "Dusk.jpg"

[[wallpapers]]
title.default = "Spring"
title.zh-CN = "一方春色"
license = "CC BY-NC-ND 4.0"
id = "Spring"
path = "Spring.jpg"

[[wallpapers]]
title.default = "Untitled Window Pic"
title.zh-CN = "冬窗"
license = "CC BY-NC-ND 4.0"
id = "Untitled_Window_Pic"
path = "Untitled_Window_Pic.jpg"
